x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  agent:
    restart: unless-stopped
    stop_grace_period: 1m
    image: ${AZTEC_REPO}:${AZTEC_TAG}
    pull_policy: always
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      PROVER_BROKER_HOST: ${BROKER_NODE}
      PROVER_AGENT_COUNT: ${PROVER_AGENT_COUNT}
      PROVER_AGENT_POLL_INTERVAL_MS: ${PROVER_AGENT_POLL_INTERVAL_MS}
      PROVER_REAL_PROOFS: "true"
      PROVER_ID: ${PROVER_ID:?error}
    command: >
      node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js
      start --prover-agent
    <<: *logging
