x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  agent:
    restart: unless-stopped
    stop_grace_period: 1m
    image: ${AZTEC_REPO}:${AZTEC_TAG}
    pull_policy: always
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: ${OTEL_METRICS_ENDPOINT}
    volumes:
      - aztec-agent-crs:/root/.bb-crs
    deploy:
      resources:
        limits:
          cpus: ${PROVER_AGENT_CPUS:-32}
          memory: ${PROVER_AGENT_MEM:-128G}
    entrypoint:
      - node
      - --no-warnings
      - /usr/src/yarn-project/aztec/dest/bin/index.js
      - start
      - --network
      - ${NETWORK}
      - --proverAgent.proverBrokerUrl
      - ${BROKER_NODE}
      - --proverAgent.proverAgentCount
      - ${PROVER_AGENT_COUNT}
      - --proverAgent.proverAgentPollIntervalMs
      - ${PROVER_AGENT_POLL_INTERVAL_MS}
      - --prover-agent
      - --auto-update
      - config
    <<: *logging
    labels:
      - com.centurylinklabs.watchtower.enable=${AZTEC_AUTOUPDATE:-false}

volumes:
  aztec-agent-crs:
