x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  broker:
    restart: unless-stopped
    stop_grace_period: 1m
    image: ${AZTEC_REPO}:${AZTEC_TAG}
    pull_policy: always
    volumes:
      - aztec-broker-data:/data
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: ${OTEL_METRICS_ENDPOINT}
    entrypoint:
      - node
      - --no-warnings
      - /usr/src/yarn-project/aztec/dest/bin/index.js
      - start
      - --data-directory
      - /data
      - --data-store-map-size-kb
      - "134217728"
      - --network
      - ${NETWORK}
      - --port
      - ${BROKER_PORT}
      - --l1-rpc-urls
      - ${L1_RPC}
      - --prover-broker
    <<: *logging

  node:
    restart: unless-stopped
    stop_grace_period: 1m
    image: ${AZTEC_REPO}:${AZTEC_TAG}
    pull_policy: always
    depends_on:
      - broker
    volumes:
      - aztec-node-data:/data
    ports:
      - ${P2P_PORT}:${P2P_PORT}/udp
      - ${P2P_PORT}:${P2P_PORT}/tcp
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: ${OTEL_METRICS_ENDPOINT}
      #L1_FIXED_PRIORITY_FEE_PER_GAS: ${L1_FIXED_PRIORITY_FEE_PER_GAS}
      #L1_GAS_LIMIT_BUFFER_PERCENTAGE: ${L1_GAS_LIMIT_BUFFER_PERCENTAGE}
      #L1_GAS_PRICE_MAX: ${L1_GAS_PRICE_MAX}
      BLOB_SINK_URL: ${BLOB_SINK_URL}
      P2P_PORT: ${P2P_PORT}
    entrypoint:
      - node
      - --no-warnings
      - /usr/src/yarn-project/aztec/dest/bin/index.js
      - start
      - --data-directory
      - /data
      - --data-store-map-size-kb
      - "134217728"
      - --network
      - ${NETWORK}
      - --p2p.p2pIp
      - ${PUBLIC_IP_ADDRESS}
      - --p2p.p2pPort
      - ${P2P_PORT}
      - --l1-rpc-urls
      - ${L1_RPC}
      - --l1-consensus-host-urls
      - ${L1_REST}
      - --proverAgent.proverBrokerUrl
      - ${BROKER_NODE}
      - --proverNode.publisherPrivateKey
      - ${L1_WALLET_PRIVATE_KEY}
      - --prover-node
      - --archiver
    <<: *logging

volumes:
  aztec-broker-data:
  aztec-node-data:
