x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  provider-monitor:
    restart: unless-stopped
    build:
      context: ./provider-monitor
      dockerfile: Dockerfile
    volumes:
      - ./aztec-validator-keystore:/keystore
      - coinbase-monitor-data:/data
    environment:
      PROVIDER_ID: ${PROVIDER_ID}
      STAKING_API_URL: ${STAKING_API_URL}
      MONITOR_POLL_INTERVAL: ${MONITOR_POLL_INTERVAL:-10800}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL:-}
      KEYSTORE_PATH: /keystore
      DATA_PATH: /data
      L1_RPC_URL: ${L1_RPC}
      NETWORK: ${NETWORK:-mainnet}
      METRICS_PORT: ${PROVIDER_MONITOR_METRICS_PORT:-9102}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=${PROVIDER_MONITOR_METRICS_PORT:-9102}
    <<: *logging

volumes:
  coinbase-monitor-data:
