x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  validator:
    restart: unless-stopped
    stop_grace_period: 1m
    image: ${AZTEC_REPO}:${AZTEC_TAG}
    pull_policy: always
    volumes:
      - aztec-validator-data:/data
      - aztec-validator-crs:/root/.bb-crs
    ports:
      - ${VALIDATOR_P2P_PORT}:${VALIDATOR_P2P_PORT}/udp
      - ${VALIDATOR_P2P_PORT}:${VALIDATOR_P2P_PORT}/tcp
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: ${OTEL_METRICS_ENDPOINT}
      BLOB_SINK_URL: ${BLOB_SINK_URL}
      P2P_PORT: ${VALIDATOR_P2P_PORT}
      GOVERNANCE_PROPOSER_PAYLOAD_ADDRESS: ${GOVERNANCE_PROPOSER_PAYLOAD_ADDRESS:-}
    entrypoint:
      - node
      - --no-warnings
      - /usr/src/yarn-project/aztec/dest/bin/index.js
      - start
      - --data-directory
      - /data
      - --network
      - ${NETWORK}
      - --p2p.p2pIp
      - ${PUBLIC_IP_ADDRESS}
      - --p2p.p2pPort
      - ${VALIDATOR_P2P_PORT}
      - --l1-rpc-urls
      - ${L1_RPC}
      - --l1-consensus-host-urls
      - ${L1_REST}
      - --sequencer.validatorPrivateKeys
      - ${VALIDATOR_PRIVATE_KEYS}
      - --sequencer.publisherPrivateKeys
      - ${L1_WALLET_PRIVATE_KEY}
      - --sequencer.coinbase
      - ${COINBASE}
      - --node
      - --archiver
      - --sequencer
      - --auto-update
      - config
    command: ${SEQUENCER_EXTRAS}
    <<: *logging
    labels:
      - com.centurylinklabs.watchtower.enable=${AZTEC_AUTOUPDATE:-false}

volumes:
  aztec-validator-data:
  aztec-validator-crs:
