x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  validator:
    restart: unless-stopped
    stop_grace_period: 1m
    image: ${AZTEC_REPO}:${AZTEC_TAG}
    pull_policy: always
    volumes:
      - aztec-validator-data:/data
    ports:
      - ${VALIDATOR_P2P_PORT}:${VALIDATOR_P2P_PORT}/udp
      - ${VALIDATOR_P2P_PORT}:${VALIDATOR_P2P_PORT}/tcp
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      BLOB_SINK_URL: ${BLOB_SINK_URL}
      P2P_PORT: ${VALIDATOR_P2P_PORT}
    entrypoint:
      - node
      - --no-warnings
      - /usr/src/yarn-project/aztec/dest/bin/index.js
      - start
      - --data-directory
      - /data
      - --network
      - ${NETWORK}
      - --p2p.p2pIp
      - ${PUBLIC_IP_ADDRESS}
      - --p2p.p2pPort
      - ${VALIDATOR_P2P_PORT}
      - --l1-rpc-urls
      - ${L1_RPC}
      - --l1-consensus-host-urls
      - ${L1_REST}
      - --sequencer.validatorPrivateKey
      - ${VALIDATOR_PRIVATE_KEY}
      - --sequencer.coinbase
      - ${COINBASE}
      - --node
      - --archiver
      - --sequencer
    <<: *logging

volumes:
  aztec-validator-data:
