x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  validator:
    restart: unless-stopped
    stop_grace_period: 1m
    image: ${AZTEC_REPO}:${AZTEC_TAG}
    pull_policy: always
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      PROVER_BROKER_HOST: ${BROKER_NODE}
      PROVER_AGENT_COUNT: ${PROVER_AGENT_COUNT}
      PROVER_AGENT_POLL_INTERVAL_MS: ${PROVER_AGENT_POLL_INTERVAL_MS}
      PROVER_REAL_PROOFS: "true"
      PROVER_ID: ${PROVER_ID:?error}
    entrypoint: >
      sh -c '
      test -z "$PEER_ID_PRIVATE_KEY" -a ! -f /var/lib/aztec/p2p-private-key && node /usr/src/yarn-project/aztec/dest/bin/index.js generate-p2p-private-key | head -1 | cut -d" " -f 3 | tee /var/lib/aztec/p2p-private-key || echo "Re-using existing P2P private key"
      test -z "$PEER_ID_PRIVATE_KEY" && export PEER_ID_PRIVATE_KEY=$(cat /var/lib/aztec/p2p-private-key)
      node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start --node --archiver --sequencer'
    volumes:
      - aztec_data:/var/lib/aztec
    <<: *logging
