name: Test ethd update

defaults:
  run:
    shell: bash

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Create .env file
        run: cp default.env .env
      - name: Fill in variables
        run: |
          source ./.github/helper.sh
          PROVER_ID=0x01
          var=PROVER_ID
          set_value_in_env
          L1_WALLET_PRIVATE_KEY=0x02
          var=L1_WALLET_PRIVATE_KEY
          set_value_in_env
          PUBLIC_IP_ADDRESS=1.2.3.4
          var=PUBLIC_IP_ADDRESS
          set_value_in_env
      - name: Test ethd update
        run: ./ethd update --debug --non-interactive
